version: "3.7"

services:
  db:
    container_name: db_test
    restart: always
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    networks:
      - proxynet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./cmd/migrator/migrations:/migrations
    env_file:
      - ./.env
    command:
      [ "-source", "file://migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up" ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxynet

networks:
  proxynet:
    driver: bridge
