// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// FrontHandler is an autogenerated mock type for the FrontHandler type
type FrontHandler struct {
	mock.Mock
}

// AddCartItems provides a mock function with given fields: w, r
func (_m *FrontHandler) AddCartItems(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminPage provides a mock function with given fields: w, r
func (_m *FrontHandler) AdminPage(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CartCheckout provides a mock function with given fields: w, r
func (_m *FrontHandler) CartCheckout(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DeleteBookFront provides a mock function with given fields: w, r
func (_m *FrontHandler) DeleteBookFront(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// EditBookFront provides a mock function with given fields: w, r
func (_m *FrontHandler) EditBookFront(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetCartItems provides a mock function with given fields: w, r
func (_m *FrontHandler) GetCartItems(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// HistoryPage provides a mock function with given fields: w, r
func (_m *FrontHandler) HistoryPage(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// LoginFront provides a mock function with given fields: w, t
func (_m *FrontHandler) LoginFront(w http.ResponseWriter, t *http.Request) {
	_m.Called(w, t)
}

// LoginPage provides a mock function with given fields: w, t
func (_m *FrontHandler) LoginPage(w http.ResponseWriter, t *http.Request) {
	_m.Called(w, t)
}

// MainPage provides a mock function with given fields: w, r
func (_m *FrontHandler) MainPage(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// RegistrationFront provides a mock function with given fields: w, r
func (_m *FrontHandler) RegistrationFront(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// RegistrationPage provides a mock function with given fields: w, r
func (_m *FrontHandler) RegistrationPage(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// RemoveCartItem provides a mock function with given fields: w, r
func (_m *FrontHandler) RemoveCartItem(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewFrontHandler creates a new instance of FrontHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFrontHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *FrontHandler {
	mock := &FrontHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
