// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/TeslaMode1X/DockerWireAPI/internal/api"
	"github.com/TeslaMode1X/DockerWireAPI/internal/config"
	"github.com/TeslaMode1X/DockerWireAPI/internal/db"
	"github.com/TeslaMode1X/DockerWireAPI/internal/domain/providers/auth"
	"github.com/TeslaMode1X/DockerWireAPI/internal/domain/providers/books"
	"github.com/TeslaMode1X/DockerWireAPI/internal/domain/providers/front"
	"github.com/TeslaMode1X/DockerWireAPI/internal/domain/providers/order"
	"github.com/TeslaMode1X/DockerWireAPI/internal/domain/providers/user"
	"log/slog"
)

// Injectors from wire.go:

func InitializeAPI(cfg *config.Config, log *slog.Logger) (*api.ServerHTTP, error) {
	sqlDB, err := db.ConnectToDB(cfg)
	if err != nil {
		return nil, err
	}
	repository := auth.ProvideSetRepository(sqlDB)
	userRepository := user.ProvideUserRepository(sqlDB)
	service := auth.ProvideSetService(repository, userRepository)
	handler := auth.ProvideSetHandler(service, log)
	userService := user.ProvideUserService(userRepository)
	userHandler := user.ProvideUserHandler(userService, log)
	booksRepository := books.ProvideSetRepository(sqlDB)
	booksService := books.ProvideSetService(booksRepository)
	booksHandler := books.ProvideSetHandler(booksService, log)
	orderRepository := order.ProvideUserRepository(sqlDB)
	v := front.ProvideSetTemplates()
	frontService := front.ProvideSetService(userRepository, repository, booksRepository, orderRepository, v)
	frontHandler := front.ProvideSetHandler(frontService, log)
	orderService := order.ProvideUserService(orderRepository)
	orderHandler := order.ProvideUserHandler(orderService, log)
	serverHTTP := api.NewServeHTTP(cfg, handler, userHandler, booksHandler, frontHandler, orderHandler)
	return serverHTTP, nil
}
