// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/TeslaMode1X/DockerWireAPI/internal/api"
	"github.com/TeslaMode1X/DockerWireAPI/internal/config"
	"log/slog"
)

// Injectors from wire.go:

func InitializeAPI(cfg *config.Config, log *slog.Logger) (*api.ServerHTTP, error) {
	serverHTTP := api.NewServeHTTP(cfg)
	return serverHTTP, nil
}
