FROM golang:1.23.3-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/migrator/booksmigrator.go .
COPY cmd/migrator/books.json .

RUN go build -o booksmigrator booksmigrator.go

CMD [ "./booksmigrator" ]
